version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TestApplication.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output TestApplication.csproj
artifacts:
  files:
    - CodeBuild-TestApplication/build_output/**/*
    - scripts/**/*
  
